spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: guli-search

server:
  port: 31011

logging:
  level:
    com.bigdata.gulimall.product: debug