spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alicloud:
      access-key: LTAI4G9niwzj7HGqPruhYFwX
      secret-key: fMJj2CQULqH1fAderxYhiWTJQGoNqt
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: guli-uptown

  application:
    name: guli-third-party

server:
  port: 30000

logging:
  level:
    com.bigdata.gulimall.product: debug